import { BuildingDefinition, BuildingType } from './types';

export const BUILDING_DEFINITIONS: Record<BuildingType, BuildingDefinition> = {
  [BuildingType.PALISADE]: {
    type: BuildingType.PALISADE,
    name: 'Palisade',
    category: 'castle',
    maxLevel: 3,
    costPerLevel: { gold: 50, food: 0, wood: 80, stone: 20, iron: 0 },
    effects: { defense: 5 },
  },
  [BuildingType.STONE_WALL]: {
    type: BuildingType.STONE_WALL,
    name: 'Steinmauer',
    category: 'castle',
    maxLevel: 3,
    costPerLevel: { gold: 100, food: 0, wood: 20, stone: 150, iron: 10 },
    effects: { defense: 15 },
  },
  [BuildingType.KEEP]: {
    type: BuildingType.KEEP,
    name: 'Bergfried',
    category: 'castle',
    maxLevel: 3,
    costPerLevel: { gold: 200, food: 0, wood: 50, stone: 200, iron: 30 },
    effects: { defense: 25, prosperity: 5 },
  },
  [BuildingType.GATEHOUSE]: {
    type: BuildingType.GATEHOUSE,
    name: 'Torhaus',
    category: 'castle',
    maxLevel: 2,
    costPerLevel: { gold: 80, food: 0, wood: 60, stone: 80, iron: 15 },
    effects: { defense: 10 },
  },
  [BuildingType.WATCHTOWER]: {
    type: BuildingType.WATCHTOWER,
    name: 'Wachturm',
    category: 'castle',
    maxLevel: 2,
    costPerLevel: { gold: 60, food: 0, wood: 40, stone: 60, iron: 5 },
    effects: { defense: 8 },
  },
  [BuildingType.BARRACKS]: {
    type: BuildingType.BARRACKS,
    name: 'Kaserne',
    category: 'military',
    maxLevel: 3,
    costPerLevel: { gold: 120, food: 0, wood: 80, stone: 60, iron: 20 },
    effects: { recruitBonus: 1 },
  },
  [BuildingType.STABLES]: {
    type: BuildingType.STABLES,
    name: 'Stallungen',
    category: 'military',
    maxLevel: 2,
    costPerLevel: { gold: 150, food: 20, wood: 100, stone: 40, iron: 25 },
    effects: { cavalryBonus: 1 },
  },
  [BuildingType.GRANARY]: {
    type: BuildingType.GRANARY,
    name: 'Vorratslager',
    category: 'castle',
    maxLevel: 3,
    costPerLevel: { gold: 70, food: 0, wood: 90, stone: 30, iron: 0 },
    effects: { foodStorage: 50 },
  },
  [BuildingType.MARKET]: {
    type: BuildingType.MARKET,
    name: 'Markt',
    category: 'city',
    maxLevel: 3,
    costPerLevel: { gold: 100, food: 0, wood: 60, stone: 40, iron: 5 },
    effects: { goldIncome: 10, prosperity: 10 },
  },
  [BuildingType.SMITHY]: {
    type: BuildingType.SMITHY,
    name: 'Schmiede',
    category: 'city',
    maxLevel: 2,
    costPerLevel: { gold: 130, food: 0, wood: 40, stone: 60, iron: 40 },
    effects: { ironIncome: 5 },
  },
  [BuildingType.WORKSHOP]: {
    type: BuildingType.WORKSHOP,
    name: 'Werkstatt',
    category: 'city',
    maxLevel: 2,
    costPerLevel: { gold: 90, food: 0, wood: 80, stone: 30, iron: 15 },
    effects: { woodIncome: 5 },
  },
  [BuildingType.TOWN_HALL]: {
    type: BuildingType.TOWN_HALL,
    name: 'Rathaus',
    category: 'city',
    maxLevel: 2,
    costPerLevel: { gold: 180, food: 0, wood: 70, stone: 100, iron: 10 },
    effects: { influence: 5, prosperity: 15 },
  },
  [BuildingType.TEMPLE]: {
    type: BuildingType.TEMPLE,
    name: 'Tempel',
    category: 'city',
    maxLevel: 2,
    costPerLevel: { gold: 150, food: 0, wood: 50, stone: 120, iron: 5 },
    effects: { morale: 5, prosperity: 8 },
  },
  [BuildingType.UNIVERSITY]: {
    type: BuildingType.UNIVERSITY,
    name: 'Universität',
    category: 'city',
    maxLevel: 1,
    costPerLevel: { gold: 300, food: 0, wood: 60, stone: 150, iron: 20 },
    effects: { influence: 15, prosperity: 20 },
  },
  [BuildingType.HARBOR]: {
    type: BuildingType.HARBOR,
    name: 'Hafen',
    category: 'city',
    maxLevel: 2,
    costPerLevel: { gold: 200, food: 0, wood: 120, stone: 80, iron: 30 },
    effects: { goldIncome: 20, trade: 1 },
  },
  [BuildingType.CITY_WALL]: {
    type: BuildingType.CITY_WALL,
    name: 'Stadtmauer',
    category: 'city',
    maxLevel: 2,
    costPerLevel: { gold: 160, food: 0, wood: 30, stone: 180, iron: 20 },
    effects: { defense: 12 },
  },
  [BuildingType.FARM]: {
    type: BuildingType.FARM,
    name: 'Bauernhof',
    category: 'village',
    maxLevel: 3,
    costPerLevel: { gold: 40, food: 0, wood: 50, stone: 10, iron: 0 },
    effects: { foodIncome: 15 },
  },
  [BuildingType.MINE]: {
    type: BuildingType.MINE,
    name: 'Mine',
    category: 'village',
    maxLevel: 3,
    costPerLevel: { gold: 80, food: 0, wood: 30, stone: 20, iron: 0 },
    effects: { stoneIncome: 8, ironIncome: 4 },
  },
  [BuildingType.LUMBER_MILL]: {
    type: BuildingType.LUMBER_MILL,
    name: 'Sägewerk',
    category: 'village',
    maxLevel: 3,
    costPerLevel: { gold: 50, food: 0, wood: 20, stone: 15, iron: 5 },
    effects: { woodIncome: 12 },
  },
};
