import type { ProvinceSeed } from './types';
import { Terrain } from './types';

export const STARTING_RESOURCES = {
  gold: 500,
  food: 300,
  wood: 200,
  stone: 150,
  iron: 75,
  influence: 20,
  fame: 0,
};

export const WORLD_PROVINCES: ProvinceSeed[] = [
  {
    name: 'Nordmark',
    x: 0,
    y: 0,
    terrain: Terrain.PLAINS,
    population: 1200,
    neighbors: ['Ostfeld', 'Westhain'],
  },
  {
    name: 'Ostfeld',
    x: 1,
    y: 0,
    terrain: Terrain.FOREST,
    population: 900,
    neighbors: ['Nordmark', 'Mittelland', 'Südhang'],
  },
  {
    name: 'Mittelland',
    x: 2,
    y: 0,
    terrain: Terrain.PLAINS,
    population: 1500,
    neighbors: ['Ostfeld', 'Goldtal', 'Bergheim'],
  },
  {
    name: 'Goldtal',
    x: 3,
    y: 0,
    terrain: Terrain.HILLS,
    population: 800,
    neighbors: ['Mittelland', 'Steinburg'],
  },
  {
    name: 'Westhain',
    x: 0,
    y: 1,
    terrain: Terrain.FOREST,
    population: 1000,
    neighbors: ['Nordmark', 'Flachland', 'Südhang'],
  },
  {
    name: 'Flachland',
    x: 1,
    y: 1,
    terrain: Terrain.PLAINS,
    population: 1800,
    neighbors: ['Westhain', 'Südhang', 'Mittelburg', 'Ostwald'],
  },
  {
    name: 'Südhang',
    x: 2,
    y: 1,
    terrain: Terrain.HILLS,
    population: 1100,
    neighbors: ['Ostfeld', 'Westhain', 'Flachland', 'Bergheim', 'Südtor'],
  },
  {
    name: 'Mittelburg',
    x: 3,
    y: 1,
    terrain: Terrain.PLAINS,
    population: 2000,
    neighbors: ['Flachland', 'Bergheim', 'Steinburg', 'Küsteneck'],
  },
  {
    name: 'Bergheim',
    x: 4,
    y: 1,
    terrain: Terrain.MOUNTAINS,
    population: 700,
    neighbors: ['Mittelland', 'Südhang', 'Mittelburg', 'Steinburg'],
  },
  {
    name: 'Steinburg',
    x: 5,
    y: 1,
    terrain: Terrain.MOUNTAINS,
    population: 600,
    neighbors: ['Goldtal', 'Mittelburg', 'Bergheim', 'Ostklippe'],
  },
  {
    name: 'Ostwald',
    x: 0,
    y: 2,
    terrain: Terrain.FOREST,
    population: 950,
    neighbors: ['Flachland', 'Südtor', 'Westufer'],
  },
  {
    name: 'Südtor',
    x: 1,
    y: 2,
    terrain: Terrain.PLAINS,
    population: 1300,
    neighbors: ['Südhang', 'Ostwald', 'Mittelburg', 'Südblick'],
  },
  {
    name: 'Südblick',
    x: 2,
    y: 2,
    terrain: Terrain.HILLS,
    population: 850,
    neighbors: ['Südtor', 'Küsteneck', 'Hafenstadt'],
  },
  {
    name: 'Küsteneck',
    x: 3,
    y: 2,
    terrain: Terrain.COAST,
    population: 1600,
    neighbors: ['Mittelburg', 'Südblick', 'Hafenstadt', 'Ostklippe'],
  },
  {
    name: 'Hafenstadt',
    x: 4,
    y: 2,
    terrain: Terrain.COAST,
    population: 2200,
    neighbors: ['Südblick', 'Küsteneck', 'Ostklippe'],
  },
  {
    name: 'Westufer',
    x: 0,
    y: 3,
    terrain: Terrain.COAST,
    population: 1400,
    neighbors: ['Ostwald', 'Südblick'],
  },
  {
    name: 'Ostklippe',
    x: 5,
    y: 2,
    terrain: Terrain.COAST,
    population: 750,
    neighbors: ['Steinburg', 'Küsteneck', 'Hafenstadt'],
  },
];

export const TERRAIN_DEFENSE_BONUS: Record<Terrain, number> = {
  [Terrain.PLAINS]: 0,
  [Terrain.FOREST]: 10,
  [Terrain.HILLS]: 15,
  [Terrain.MOUNTAINS]: 25,
  [Terrain.COAST]: 5,
};

export const CASTLE_DEFENSE_PER_LEVEL = 20;
