import { UnitDefinition, UnitType } from './types';

export const UNIT_DEFINITIONS: Record<UnitType, UnitDefinition> = {
  [UnitType.MILITIA]: {
    type: UnitType.MILITIA,
    attack: 3,
    defense: 2,
    speed: 4,
    morale: 50,
    upkeep: 1,
    gold: 10,
    food: 5,
    wood: 0,
    stone: 0,
    iron: 0,
    recruitTime: 1,
  },
  [UnitType.SPEARMAN]: {
    type: UnitType.SPEARMAN,
    attack: 5,
    defense: 6,
    speed: 3,
    morale: 60,
    upkeep: 2,
    gold: 20,
    food: 8,
    wood: 5,
    stone: 0,
    iron: 2,
    recruitTime: 2,
  },
  [UnitType.ARCHER]: {
    type: UnitType.ARCHER,
    attack: 7,
    defense: 3,
    speed: 4,
    morale: 55,
    upkeep: 2,
    gold: 25,
    food: 6,
    wood: 10,
    stone: 0,
    iron: 3,
    recruitTime: 2,
  },
  [UnitType.SWORDSMAN]: {
    type: UnitType.SWORDSMAN,
    attack: 8,
    defense: 7,
    speed: 3,
    morale: 70,
    upkeep: 3,
    gold: 35,
    food: 10,
    wood: 0,
    stone: 0,
    iron: 8,
    recruitTime: 3,
  },
  [UnitType.CROSSBOWMAN]: {
    type: UnitType.CROSSBOWMAN,
    attack: 9,
    defense: 4,
    speed: 2,
    morale: 65,
    upkeep: 3,
    gold: 40,
    food: 8,
    wood: 5,
    stone: 0,
    iron: 10,
    recruitTime: 3,
  },
  [UnitType.LIGHT_CAVALRY]: {
    type: UnitType.LIGHT_CAVALRY,
    attack: 8,
    defense: 5,
    speed: 8,
    morale: 75,
    upkeep: 4,
    gold: 50,
    food: 15,
    wood: 0,
    stone: 0,
    iron: 12,
    recruitTime: 4,
  },
  [UnitType.HEAVY_CAVALRY]: {
    type: UnitType.HEAVY_CAVALRY,
    attack: 12,
    defense: 8,
    speed: 5,
    morale: 80,
    upkeep: 6,
    gold: 80,
    food: 20,
    wood: 0,
    stone: 0,
    iron: 20,
    recruitTime: 5,
  },
  [UnitType.KNIGHT]: {
    type: UnitType.KNIGHT,
    attack: 15,
    defense: 12,
    speed: 6,
    morale: 90,
    upkeep: 8,
    gold: 120,
    food: 25,
    wood: 0,
    stone: 0,
    iron: 30,
    recruitTime: 6,
  },
};

export function getUnitPower(type: UnitType, count: number): { attack: number; defense: number } {
  const def = UNIT_DEFINITIONS[type];
  return {
    attack: def.attack * count,
    defense: def.defense * count,
  };
}
